server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-course-provider  #匹配后提供服务的路由地址
          predicates:
            - Path=/course/list/**   #断言,路径相匹配的进行路由

        - id: payment_routh1
          uri: lb://nacos-course-provider
          predicates:
            - Path=/car/add/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://nacos-course-provider
          predicates:
             - Path=/car/list/**   #断言,路径相匹配的进行路由

        - id: payment_routh3
          uri: lb://nacos-course-provider
          predicates:
            - Path=/car/xgnum/**   #断言,路径相匹配的进行路由

        - id: payment_routh4
          uri: lb://nacos-course-provider
          predicates:
            - Path=/car/del/**   #断言,路径

        - id: payment_routh5
          uri: lb://nacos-course-provider
          predicates:
            - Path=/user/list/**   #断言,路径相匹配的进行路由

        - id: payment_routh6
          uri: lb://nacos-order-provider
          predicates:
            - Path=/order/jiesuan**   #断言,路径相匹配的进行路由

        - id: payment_routh7
          uri: lb://nacos-email-provider
          predicates:
            - Path=/order/xq**   #断

